# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P3_PAR_IMPAR.UI'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 445)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_checar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_checar.setGeometry(QtCore.QRect(170, 330, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_checar.setFont(font)
        self.btn_checar.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"border-radius: 10px;")
        self.btn_checar.setObjectName("btn_checar")
        self.txt_n = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_n.setGeometry(QtCore.QRect(200, 120, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_n.setFont(font)
        self.txt_n.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_n.setObjectName("txt_n")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 120, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.btn_limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_limpiar.setGeometry(QtCore.QRect(470, 190, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_limpiar.setFont(font)
        self.btn_limpiar.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 111, 71))
        self.label_4.setStyleSheet("border: 5px solid white;\n"
"border-radius: 10px;\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Logos/Imagenes/logo uat.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 10, 111, 71))
        self.label_2.setStyleSheet("border: 5px solid red;\n"
"border-radius: 10px;\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Logos/Imagenes/logo fians.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 340, 111, 71))
        self.label_3.setStyleSheet("border: 5px solid black;\n"
"border-radius: 10px;\n"
"")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Logos/Imagenes/equipo.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_checar.setText(_translate("MainWindow", "CHECAR SI ES PAR"))
        self.txt_n.setText(_translate("MainWindow", "H"))
        self.label.setText(_translate("MainWindow", "Numero:"))
        self.btn_limpiar.setText(_translate("MainWindow", "LIMPIAR"))
import recursos_rc
